include::../attribute.adoc[]

== はじめに

本文書は ``Asciidoc`` とそのRubyによる実装である ``Asciidoctor`` を用いてAsciidoc文書を執筆する環境を構築する手順を示します。実行環境はWindows、Linux、macOSの各OSに対応しています。

この文書の手順により以下のことができるようになります。
[format="csv",cols="2,1"]
[frame="topbot",grid="none"]
|======
Asciidoc形式で執筆した文書をHTML/PDF形式に変換する。,Asciidoc文書変換用スクリプト
変換結果をリアルタイムにプレビューしながら、エディターで文書を編集する。,Visual Studio Code拡張設定
|======

Asciidocは表現力の高い文書をテキストファイルベースで執筆できるテキストプロセッサーです。他の軽量テキストプロセッサーが持たない文書間のインクルードやソースコードの挿入などの機能も有し、かつ簡潔です。特に技術文書の執筆には大きな力を発揮することでしょう。

[TIP]
====
Asciidocでこのような脚注を表現することができます。Asciidocの高い表現力を示す一つの例です。
====

一般的にこのようなテキストプロセッサーを用いた執筆環境を構築するためには多くの準備が必要となりますが、本文書の手順は極力初期導入するプロダクトを少なく、簡単に快適な執筆環境を整えられるよう考えています。

具体的には文書の変換に、実行をJVM環境だけに依存する ``Asciidoctorj`` と ``Gradle`` を活用し、執筆環境については ``Visual Studio Code`` を用いることでリアルタイムに文書をプレビューしながら、最後にコマンド一つでPDF化できるように準備してあります。

本文書がみなさんの執筆活動のお手伝いになれば幸いです。

### 謝辞

本文書の手順の実装であるビルドスクリプトやテーマでは次のプロダクトと技術資料が使われています。

NOTE: プロダクト名の隣にライセンスを併記しました。商用利用等で制限のあるプロダクトはありませんが、それぞれライセンスを確認してください。

Font::
  * 源真ゴシック - SIL Open Font License 1.1 - http://jikasei.me/font/genshin/
